export class Companie
	{
			 Id:number;
			 CompanyCode:string;
			 CompanyName:string;
			 OtherBusinessName1:string;
			 Address1:string;
			 Address2:string;
			 Address3:string;
			 Telephone:string;
			 Mobile:string;
			 FaxNo:string;
			 Email:string;
			 WebAddress:string;
			 ContactPerson:string;
			 TaxID1:number;
			 TaxID2:number;
			 TaxRegistrationNumber1:string;
			 TaxRegistrationNumber2:string;
			 StartOfFiscalYear:number;
			 CostingMethod:string;
			 IsVat:boolean;
			 IsDelete:boolean;
			 GroupOfCompanyID:number;
			 CreatedUser:number;
			 CreatedDate:Date;
			 ModifiedUser:number;
			 ModifiedDate:Date;
			 DataTransfer:number;
	}