export class Customer
	{
			 Id:number;
			 CustomerCode:string;
			 CustomerTitle:number;
			 CustomerName:string;
			 CustomerType:number;
			 ContactPersonName:string;
			 Gender:number;
			 Address1:string;
			 Address2:string;
			 Address3:string;
			 Email:string;
			 CreditLimit:number;
			 ChequeLimit:number;
			 Outstanding:number;
			 CustomerImage:string;
			 Remark:string;
			 IsSuspended:boolean;
			 IsBlackListed:boolean;
			 IsCreditAllowed:boolean;
			 IsActive:boolean;
			 GroupOfCompanyID:number;
			 CreatedUser:number;
			 CreatedDate:Date;
			 ModifiedUser:number;
			 ModifiedDate:Date;
			 DataTransfer:number;
	}