export class Vehicle
	{
			 Id:number;
			 CreditCusId:number;
			 RFID_Id:number;
			 CreditLimit:number;
			 ChequeLimit:number;
			 Outstanding:number;
			 RFIDNo:string;
			 RegistrationNo:string;
			 VehicleName:string;
			 EngineNo:string;
			 ChassesNo:string;
			 VehicleType:string;
			 FuelType:string;
			 Make:string;
			 Model:string;
			 EngineCapacity:string;
			 Weight:number;
			 Remark:string;
			 VehicleImage:string;
			 GroupOfCompanyID:number;
			 CreatedUser:number;
			 CreatedDate:Date;
			 ModifiedUser:number;
			 ModifiedDate:Date;
			 DataTransfer:number;
	}
